language: rust
sudo: false
matrix:
  include:
    - rust: 1.0.0
    - rust: 1.1.0
    - rust: 1.2.0
    - rust: 1.3.0
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      env:
       - FEATURES='test'
       - BENCH=1
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES") &&
      cargo doc --verbose --features "$FEATURES"
