[package]

name = "petgraph"
version = "0.3.0-alpha.1"
license = "MIT/Apache-2.0"
authors = [
"bluss",
"mitchmindtree",
]

description = "Graph data structure library. Provides graph types and graph algorithms."
documentation = "https://docs.rs/petgraph/"
repository = "https://github.com/bluss/petgraph"

keywords = ["data-structure", "graph", "unionfind", "graph-algorithms"]

[lib]

name = "petgraph"
bench = false

[profile.release]

[profile.bench]
debug = true

[dependencies]
fixedbitset = "0.1.0"
quickcheck = { optional = true, version = "0.3" }
itertools = "0.5"

[dev-dependencies]
rand = "0.3"

[features]
# For unstable features
generate = []
unstable = ["generate"]
default = ["stable_graph"]
stable_graph = []

# feature flags for testing use only
test = []
all = ["test", "unstable", "quickcheck"]
