[package]

name = "petgraph"
version = "0.2.0"
license = "MIT/Apache-2.0"
authors = [
"bluss",
"mitchmindtree",
]

description = "Graph data structure library. Provides graph types and graph algorithms."
documentation = "http://bluss.github.io/petulant-avenger-graphlibrary"
repository = "https://github.com/bluss/petulant-avenger-graphlibrary"

keywords = ["data-structure", "graph", "unionfind", "graph-algorithms"]

[lib]

name = "petgraph"

[profile.release]

[profile.bench]
debug = true

[dependencies]
fixedbitset = "0.1.0"
quickcheck = { optional = true, version = "0.2.24" }

[dev-dependencies]
rand = "0.3"

[features]

test = []
