[package]

name = "petgraph"
version = "0.0.2"
authors = ["bluss"]
license = "MIT/Apache-2.0"

description = "Graph data structure."
documentation = "http://bluss.github.io/petulant-avenger-graphlibrary/target/doc/petgraph"
repository = "https://github.com/bluss/petulant-avenger-graphlibrary"

keywords = ["container", "data-structure", "graph", "unionfind"]

[lib]

name = "petgraph"
